// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALx5VwsJVS-cg7oO_ktv6ivtqHi34THxs',
    appId: '1:82433493313:web:f29f64ea6d1ced7c1979c0',
    messagingSenderId: '82433493313',
    projectId: 'ashtontennisklub',
    authDomain: 'ashtontennisklub.firebaseapp.com',
    storageBucket: 'ashtontennisklub.appspot.com',
    measurementId: 'G-5X1JQBBE2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqAL7R58jz9ImKE4sSiITs6uztKoseqpU',
    appId: '1:82433493313:android:51bce51dbe8741f71979c0',
    messagingSenderId: '82433493313',
    projectId: 'ashtontennisklub',
    storageBucket: 'ashtontennisklub.appspot.com',
  );

}